### ISSUE TITLE
Write Message Window

### ISSUE THREAD

**Issue by pltsmt** [Aris-t2/CustomizeMyBird#11]
The header of the Write message menu is all white.  Is there an option that I've not managed to change the color as in the primary user interface?
![capture](https://user-images.githubusercontent.com/44144844/46921254-a98b1380-cfbe-11e8-96b8-209daedc4129.JPG)

**Comment by Aris-t2** [comment]
You should not use the new "Glass" options without Glass8 software.
See changelog:
https://github.com/Aris-t2/CustomizeMyBird/releases/tag/2.6
https://addons.thunderbird.net/en-us/thunderbird/addon/customizemybird/versions/?page=1#version-2.6

**Comment by Aris-t2** [comment]
I see the issue. Not sure, if it was present in GMF before, but could you test **_CMB_v2.6_2018.10.14.xpi_** from here: https://github.com/Aris-t2/CustomizeMyBird/releases/tag/2.6

**Comment by pltsmt** [comment]
I've installed the one you said to use... attached is the screenshot showing in the yellow markup it's all still white.
![capture](https://user-images.githubusercontent.com/44144844/46921684-1fde4480-cfc4-11e8-92a9-f5856c714345.JPG)

**Comment by pltsmt** [comment]
What is the Glass8 software that you mentioned?  I am running Windows 10.

**Comment by Aris-t2** [comment]
Glass8 ( http://glass8.eu/ ) restores the window transparency known from Windows 7 on Windows 8 and 10. The new options are mainly for that. If you are using Windows 10s color options to colorize system titlebars, the marked area will be colorized as well. 
Do not use Glass options, if you are using Windows 10s default ui and settings.

**Comment by Aris-t2** [comment]
Fixed in CMB 2.7.

**Comment by pltsmt** [comment]
Thank-you for all the understanding and fixes!  This is truly the greatest addon I've ever used.  Would love to see you write a stationery addon!  :)

**Comment by Aris-t2** [comment]
Thanks.

**Comment by pltsmt** [comment]
In the 2.7 update, the tabs that I highlighted in red have blurred corners.  Is this something I did, or something else?

![capture](https://user-images.githubusercontent.com/44144844/47248975-1134ca80-d3d4-11e8-969d-38c098c80735.JPG)

**Comment by Aris-t2** [comment]
Set border radius value to 0 inside CMBs preferences area.

![123](https://user-images.githubusercontent.com/6013569/47252129-bdf86180-d43f-11e8-84d8-85f155924ea6.png)
