### ISSUE TITLE
Hide status bar toggle does not work

### ISSUE THREAD

**Issue by JIPG2** [Aris-t2/CustomizeMyBird#12]
The toggle to hide or not the status bar does not take effect.
Additionally, find enclosed the full Spanish translation.
[prefs.dtd.zip](https://github.com/Aris-t2/CustomizeMyBird/files/2489307/prefs.dtd.zip)

**Comment by Aris-t2** [comment]
Thanks for the note and translation update. Next update will take care of the issue.

**Comment by Aris-t2** [comment]
Fixed in CMB 2.7.
