### ISSUE TITLE
[Fx60-63] 'about:preferences tab' settings get wrongly applied to 'Options' window

### ISSUE THREAD

**Issue by artasher** [Aris-t2/CustomizeMyBird#14]
Problem when using Options with Lightning and CusomizeMyBird.
Using Thunderbird 60.3.0

See Bugzilla issue 1503441:  https://bugzilla.mozilla.org/show_bug.cgi?id=1503441

Thanks

**Comment by Aris-t2** [comment]
I think you are using the add-on wrong. It looks like you have enabled settings exclusively made for Windows 7s Aero Glass, but on your screenshots I see you are using OSs Aero Basic theme.

**Comment by Aris-t2** [comment]
Can you confirm the issue only happens when "GMF" related settings are enabled?

![1](https://user-images.githubusercontent.com/6013569/48012951-7baf6f80-e123-11e8-9185-254b107a8979.png)

**Comment by mthoms27** [comment]
Hi,
I confirm troubles with the options > calendar button when using the add-on (2.7.4). In my case it started 10 nov.2018 when I upgraded Thunderbird from 52.9 to 60.3. As reported in https://bugzilla.mozilla.org/show_bug.cgi?id=1503441 the Option window partially dissappears, and TB is frozen. This happens also when all other add-ons are disabled. Solution: Have to exit TB with taskmanager. Then restart TB and disable CMB, and put the options menu on another tab. (Hope this description of the problem can help you).

**Comment by Aris-t2** [comment]
Actually it would be good to know, which settings are used and whether the above GMF options are enabled or not.

**Comment by Aris-t2** [comment]
I meant the settings on CMBs settings window/tab.

Uninstall CMB, restart Thunderbird and reinstall CMB.
The restart is very important!

**Comment by Aris-t2** [comment]
OK, found the issue.

Mozilla supposed to switch preferences from window to a tab in Tb60+, but still did not. The option causing this issue is the "alternative appearance" for about:preferences. Disable the option like seen on this screenshot:

![123](https://user-images.githubusercontent.com/6013569/48313766-4bebe600-e5c1-11e8-86b0-d92418c94889.png)

**Comment by mthoms27** [comment]
Thank you Aris, that did the trick !

**Comment by Aris-t2** [comment]
Just uploaded new version to Github and AMO.
