### ISSUE TITLE
[Tb60+] Add-on manager loses 'Restart now' link when add-on version numbers are shown

### ISSUE THREAD

**Issue by TimRude** [Aris-t2/CustomizeMyBird#17]
In the CustomizeMyBird options, under the 'Add-on manager (about:addons)' heading, if the 'Show add-ons current version number' option is checked, it prevents the Add-on manager from showing the 'Restart now' link when any add-on in the list is enabled/disabled and a restart is required.

TB 60.3.1 on Windows 7 (32)
CustomizeMyBird 2.7.5

**Comment by Aris-t2** [comment]
Please install the latest version of this add-on from here: https://github.com/Aris-t2/CustomizeMyBird/releases and give me some feedback about the state of the issue. It might be required to restart Thunderbird once even, if this a restartless add-on.

Use **CMB_v2.7.5.3.xpi**, if you want to get updates from here (Github) or **CMB_v2.7.5.3-ATN.xpi** to get future updates from addons.thunderbird.net only I upload a new version there. 2.7.5.x builds are currently only on Github.

**Comment by TimRude** [comment]
Aris,

2.7.5.3 solves the missing 'Restart now' link issue. Thanks!

One new (I think) issue with this version that I see is on the CustomizeMyBird options screen. If you check the 'Compact view' box under the 'Add-on manager (about:addons)' heading, it immediately makes the the font size larger on the CustomizeMyBird options screen and moves everything down screen a bit, while leaving the mouse cursor where it was. Kind of disconcerting when the box you just checked jumps out from under your cursor. Finding and unchecking the box sets the font size back to where it was, and jumps the box back out from under the mouse again as it moves back up screen.

Tim Rude
...

**Comment by Aris-t2** [comment]
This should not have happened ;-)

Install 2.7.5.4.

**Comment by TimRude** [comment]
Yep. That fixes it. Thanks!
