### ISSUE TITLE
Little issue with message header on collapsed threads

### ISSUE THREAD

**Issue by bubingator** [Aris-t2/CustomizeMyBird#18]
I mean this:
![cmt1](https://user-images.githubusercontent.com/45842472/49922656-ebafd300-fee3-11e8-913b-feda6432f5c9.png)

**Comment by Aris-t2** [comment]
I need more into about your configuration and Thunderbird version.
Post a full window screenshot, but mask any "content" like names or personal info.

- Thunderbird version
- CMB version, if not 2.7.7
- window layout
- does this happen for all mails or just this one?
- does this happen without CMB installed?
- which CMB option corrupts the ui?

**Comment by bubingator** [comment]
Yes, sorry:
TB - latest 60.3.3 x32, 
CMB - 2.7.7 latest ATN, 
win 10 x64 1809, 
TB - in windowed mode or fullscreen - the same, or you mean this?: 

![2018-12-14_103328](https://user-images.githubusercontent.com/45842472/49981702-bfe82800-ff8b-11e8-8c48-f805c2ed7b17.jpg)

Just for the test, I created a new profile, added a POP3 account and installed the CMB from ATN. I did not make ANY settings in TB or CMB. Then clicked on any collapsed thread and:

![2018-12-14_104135](https://user-images.githubusercontent.com/45842472/49982201-ff177880-ff8d-11e8-9779-493a19a74340.jpg)

when I turned off the CMB:

![2018-12-14_104300](https://user-images.githubusercontent.com/45842472/49982246-3423cb00-ff8e-11e8-87e5-a683e981ad6f.jpg)

when I expanded the thread:

![2018-12-14_104353](https://user-images.githubusercontent.com/45842472/49982280-5f0e1f00-ff8e-11e8-8476-a280fecbdec3.jpg)

CMB on, full window screenshot:

![2018-12-14_105929](https://user-images.githubusercontent.com/45842472/49982589-e3ad6d00-ff8f-11e8-8e40-7585ac65680e.jpg)

Hope this helps.

**Comment by Aris-t2** [comment]
Test 2.7.7.1: https://github.com/Aris-t2/CustomizeMyBird/releases/tag/2.7.7.1

**Comment by bubingator** [comment]
Works fine now, thank you!
