### ISSUE TITLE
"Tabs: Default Thunderbird tabs" interferes with default style

### ISSUE THREAD

**Issue by ThisIsABug** [Aris-t2/CustomizeMyBird#19]
I am going to be very lazy here, sry :)

![customizemybird](https://user-images.githubusercontent.com/19193534/51141523-cba86200-1849-11e9-87dc-df7d26995b57.png)

**Comment by Aris-t2** [comment]
I will look into it.

**Comment by Aris-t2** [comment]
What DPI level are you using?

I don't see this glitch on 100% and 125%. Does changing tab height have any effect on this glitch?

![123](https://user-images.githubusercontent.com/6013569/51198875-c30d6580-18f5-11e9-977d-f4c879c5026d.png)

**Comment by ThisIsABug** [comment]
It only happens when the window is maximized, sorry I forgot about that.
My DPI level is 100%.
Tab height doesn't seem to affect the issue.

**Comment by Aris-t2** [comment]
My bad, I should have noticed the maximized icon ;-)

Test **CMB_v2.7.9r1.xpi** from here: https://github.com/Aris-t2/CustomizeMyBird/releases/tag/2.7.8

**Comment by ThisIsABug** [comment]
Works!aaaround :D
It's not blurry anymore.
Personally I love this (because my ocd doesn't kick in anymore when it's as sharp as  the rest), thank you.
Practically the issue just moved from a blurry button to a displaced frost effect :D
Do you know the identifier of the frost effect? I would like to get rid of it through userChrome.css
I can't get the inspector to work with the messenger.xul in a way that changes - made in inspector - directly change something on the mail-client. So finding identifiers is a bit cumbersome.

**Comment by Aris-t2** [comment]
It depends on your Tb version, but this should cover Tb52-66+:

```css
#tabs-toolbar::after,
#tabs-toolbar::before,
#navigation-toolbox::before,
#navigation-toolbox::after {
  box-shadow: none !important;
}
```

**Comment by ThisIsABug** [comment]
Awesome, thank you :)
