### ISSUE TITLE
[macOS][Tb52-56] Not enough space between caption buttons and tabs

### ISSUE THREAD

**Issue by SERISET** [Aris-t2/CustomizeMyBird#2]
![capture d ecran 2018-04-08 a 6 51 17 p m](https://user-images.githubusercontent.com/38193921/38473418-dffb642e-3b5d-11e8-8e45-d2fb1d3def6d.png)

**Comment by Aris-t2** [comment]
Install 2.0.7 to fix the issue on Tb52-56 or move to Thunderbird 60 beta.
