### ISSUE TITLE
Adiar todas as tarefas do calendário

### ISSUE THREAD

**Issue by rrjunior** [Aris-t2/CustomizeMyBird#23]
When I try to postpone calendar tasks all at once, it doesn't work. I have to postpone one at a time. I think is because CustomizeMyBird extension

**Comment by Aris-t2** [comment]
English only please!

This project is only about modifying the ui of Thunderbird using CustomizeMaBird add-on, this is not a Thunderbird support forum. Use Mozillazine for that: http://forums.mozillazine.org/viewforum.php?f=50
