### ISSUE TITLE
Why is my profile blocl

### ISSUE THREAD

**Issue by Canboy1706** [Aris-t2/CustomizeMyBird#7]

**Comment by Canboy1706** [comment]
Why is my profile blocked. I was trying out your apps, extensions, themes etc. ùi am maybe not familiar with the procedures but this is the first time I am doing this.

**Comment by Aris-t2** [comment]
I have no idea what you are talking about. Maybe you need admin rights to access your profile, but my add-ons are installed through Thunderbird, so I can not tell you what is causing that issue for you.
