### ISSUE TITLE
Tab height HUGE

### ISSUE THREAD

**Issue by imora12** [Aris-t2/CustomizeMyBird#8]
I was playing with tab height setting and I entered a large number by accident, tabs now take up whole screen and I can't read or navigate at all. I have to restart in safe mode and disable addon. Where can i find the setting to reset or change tab height when I enable addon again?

**Comment by Aris-t2** [comment]
Open your Thunderbird profile folder and edit prefs.js file.
`C:\Users\your name\AppData\Roaming\Thunderbird\Profiles\ id.default\prefs.js`
Search for
`extensions.customizemybirdextension.tabheight`

**Comment by imora12** [comment]
Thank you ! That did it.
