### ISSUE TITLE
Clip icon in attachment bar broken

### ISSUE THREAD

**Issue by JIPG2** [Aris-t2/CustomizeMyBird#9]
When you select in Icon Style any other option than "default" or "Noia", when the attachment bar appear at the bottom line while you write  a message (e.g. when you type the word "attachment"), the "clip" icon on the left  looks broken:

![clip](https://user-images.githubusercontent.com/43722308/46257366-96ede600-c4b8-11e8-9746-f553176d8eeb.jpg)

**Comment by Aris-t2** [comment]
This issue should be gone in version 2.4.2.
